#alias 
alias ll='ls -lhtFa'
alias cl='clear'
alias tree="tree -A"

#display 
PS1="\[\e[0;34m\]\u@\[\e[0;34m\]\h\[\e[1;33m\]:\[\e[0;33m\]\w\[\e[1;31m\]\$ \[\e[0m"

#For Other user,like 'root'
#PS1="\[\e[1;36m\]\u\[\e[0;33m\]@\[\e[1;36m\]\h:\[\e[0;34m\]\w\[\e[1;31m\]\$ \[\e[0m"
